check_reverse_errno_number ESysEPERM 1 "/* Operation not permitted */"
check_reverse_errno_number ESysENOENT 2 "/* No such file or directory */"
check_reverse_errno_number ESysESRCH 3 "/* No such process */"
check_reverse_errno_number ESysEINTR 4 "/* Interrupted system call */"
check_reverse_errno_number ESysEIO 5 "/* Input/output error */"
check_reverse_errno_number ESysENXIO 6 "/* Device not configured */"
check_reverse_errno_number ESysE2BIG 7 "/* Argument list too long */"
check_reverse_errno_number ESysENOEXEC 8 "/* Exec format error */"
check_reverse_errno_number ESysEBADF 9 "/* Bad file descriptor */"
check_reverse_errno_number ESysECHILD 10 "/* No child processes */"
check_reverse_errno_number ESysEDEADLK 11 "/* Resource deadlock avoided */"
check_reverse_errno_number ESysENOMEM 12 "/* Cannot allocate memory */"
check_reverse_errno_number ESysEACCES 13 "/* Permission denied */"
check_reverse_errno_number ESysEFAULT 14 "/* Bad address */"
check_reverse_errno_number ESysENOTBLK 15 "/* Block device required */"
check_reverse_errno_number ESysEBUSY 16 "/* Device / Resource busy */"
check_reverse_errno_number ESysEEXIST 17 "/* File exists */"
check_reverse_errno_number ESysEXDEV 18 "/* Cross-device link */"
check_reverse_errno_number ESysENODEV 19 "/* Operation not supported by device */"
check_reverse_errno_number ESysENOTDIR 20 "/* Not a directory */"
check_reverse_errno_number ESysEISDIR 21 "/* Is a directory */"
check_reverse_errno_number ESysEINVAL 22 "/* Invalid argument */"
check_reverse_errno_number ESysENFILE 23 "/* Too many open files in system */"
check_reverse_errno_number ESysEMFILE 24 "/* Too many open files */"
check_reverse_errno_number ESysENOTTY 25 "/* Inappropriate ioctl for device */"
check_reverse_errno_number ESysETXTBSY 26 "/* Text file busy */"
check_reverse_errno_number ESysEFBIG 27 "/* File too large */"
check_reverse_errno_number ESysENOSPC 28 "/* No space left on device */"
check_reverse_errno_number ESysESPIPE 29 "/* Illegal seek */"
check_reverse_errno_number ESysEROFS 30 "/* Read-only file system */"
check_reverse_errno_number ESysEMLINK 31 "/* Too many links */"
check_reverse_errno_number ESysEPIPE 32 "/* Broken pipe */"
check_reverse_errno_number ESysEDOM 33 "/* Numerical argument out of domain */"
check_reverse_errno_number ESysERANGE 34 "/* Result too large */"
check_reverse_errno_number ESysEAGAIN 35 "/* Resource temporarily unavailable */"
check_reverse_errno_number ESysEWOULDBLOCK EAGAIN "/* Operation would block */"
check_reverse_errno_number ESysEINPROGRESS 36 "/* Operation now in progress */"
check_reverse_errno_number ESysEALREADY 37 "/* Operation already in progress */"
check_reverse_errno_number ESysENOTSOCK 38 "/* Socket operation on non-socket */"
check_reverse_errno_number ESysEDESTADDRREQ 39 "/* Destination address required */"
check_reverse_errno_number ESysEMSGSIZE 40 "/* Message too long */"
check_reverse_errno_number ESysEPROTOTYPE 41 "/* Protocol wrong type for socket */"
check_reverse_errno_number ESysENOPROTOOPT 42 "/* Protocol not available */"
check_reverse_errno_number ESysEPROTONOSUPPORT 43 "/* Protocol not supported */"
check_reverse_errno_number ESysESOCKTNOSUPPORT 44 "/* Socket type not supported */"
check_reverse_errno_number ESysENOTSUP 45 "/* Operation not supported */"
check_reverse_errno_number ESysEOPNOTSUPP ENOTSUP "/* Operation not supported on socket */"
check_reverse_errno_number ESysEPFNOSUPPORT 46 "/* Protocol family not supported */"
check_reverse_errno_number ESysEAFNOSUPPORT 47 "/* Address family not supported by protocol family */"
check_reverse_errno_number ESysEADDRINUSE 48 "/* Address already in use */"
check_reverse_errno_number ESysEADDRNOTAVAIL 49 "/* Can't assign requested address */"
check_reverse_errno_number ESysENETDOWN 50 "/* Network is down */"
check_reverse_errno_number ESysENETUNREACH 51 "/* Network is unreachable */"
check_reverse_errno_number ESysENETRESET 52 "/* Network dropped connection on reset */"
check_reverse_errno_number ESysECONNABORTED 53 "/* Software caused connection abort */"
check_reverse_errno_number ESysECONNRESET 54 "/* Connection reset by peer */"
check_reverse_errno_number ESysENOBUFS 55 "/* No buffer space available */"
check_reverse_errno_number ESysEISCONN 56 "/* Socket is already connected */"
check_reverse_errno_number ESysENOTCONN 57 "/* Socket is not connected */"
check_reverse_errno_number ESysESHUTDOWN 58 "/* Can't send after socket shutdown */"
check_reverse_errno_number ESysETOOMANYREFS 59 "/* Too many references: can't splice */"
check_reverse_errno_number ESysETIMEDOUT 60 "/* Operation timed out */"
check_reverse_errno_number ESysECONNREFUSED 61 "/* Connection refused */"
check_reverse_errno_number ESysELOOP 62 "/* Too many levels of symbolic links */"
check_reverse_errno_number ESysENAMETOOLONG 63 "/* File name too long */"
check_reverse_errno_number ESysEHOSTDOWN 64 "/* Host is down */"
check_reverse_errno_number ESysEHOSTUNREACH 65 "/* No route to host */"
check_reverse_errno_number ESysENOTEMPTY 66 "/* Directory not empty */"
check_reverse_errno_number ESysEPROCLIM 67 "/* Too many processes */"
check_reverse_errno_number ESysEUSERS 68 "/* Too many users */"
check_reverse_errno_number ESysEDQUOT 69 "/* Disc quota exceeded */"
check_reverse_errno_number ESysESTALE 70 "/* Stale NFS file handle */"
check_reverse_errno_number ESysEREMOTE 71 "/* Too many levels of remote in path */"
check_reverse_errno_number ESysEBADRPC 72 "/* RPC struct is bad */"
check_reverse_errno_number ESysERPCMISMATCH 73 "/* RPC version wrong */"
check_reverse_errno_number ESysEPROGUNAVAIL 74 "/* RPC prog. not avail */"
check_reverse_errno_number ESysEPROGMISMATCH 75 "/* Program version wrong */"
check_reverse_errno_number ESysEPROCUNAVAIL 76 "/* Bad procedure for program */"
check_reverse_errno_number ESysENOLCK 77 "/* No locks available */"
check_reverse_errno_number ESysENOSYS 78 "/* Function not implemented */"
check_reverse_errno_number ESysEFTYPE 79 "/* Inappropriate file type or format */"
check_reverse_errno_number ESysEAUTH 80 "/* Authentication error */"
check_reverse_errno_number ESysENEEDAUTH 81 "/* Need authenticator */"
check_reverse_errno_number ESysEPWROFF 82 "/* Device power is off */"
check_reverse_errno_number ESysEDEVERR 83 "/* Device error, e.g. paper out */"
check_reverse_errno_number ESysEOVERFLOW 84 "/* Value too large to be stored in data type */"
check_reverse_errno_number ESysEBADEXEC 85 "/* Bad executable */"
check_reverse_errno_number ESysEBADARCH 86 "/* Bad CPU type in executable */"
check_reverse_errno_number ESysESHLIBVERS 87 "/* Shared library version mismatch */"
check_reverse_errno_number ESysEBADMACHO 88 "/* Malformed Macho file */"
check_reverse_errno_number ESysECANCELED 89 "/* Operation canceled */"
check_reverse_errno_number ESysEIDRM 90 "/* Identifier removed */"
check_reverse_errno_number ESysENOMSG 91 "/* No message of desired type */   "
check_reverse_errno_number ESysEILSEQ 92 "/* Illegal byte sequence */"
check_reverse_errno_number ESysENOATTR 93 "/* Attribute not found */"
check_reverse_errno_number ESysEBADMSG 94 "/* Bad message */"
check_reverse_errno_number ESysEMULTIHOP 95 "/* Reserved */"
check_reverse_errno_number ESysENODATA 96 "/* No message available on STREAM */"
check_reverse_errno_number ESysENOLINK 97 "/* Reserved */"
check_reverse_errno_number ESysENOSR 98 "/* No STREAM resources */"
check_reverse_errno_number ESysENOSTR 99 "/* Not a STREAM */"
check_reverse_errno_number ESysEPROTO 100 "/* Protocol error */"
check_reverse_errno_number ESysETIME 101 "/* STREAM ioctl timeout */"
check_reverse_errno_number ESysEOPNOTSUPP 102 "/* Operation not supported on socket */"
check_reverse_errno_number ESysENOPOLICY 103 "/* No such policy registered */"
check_reverse_errno_number ESysENOTRECOVERABLE 104 "/* State not recoverable */"
check_reverse_errno_number ESysEOWNERDEAD 105 "/* Previous owner died */"
check_reverse_errno_number ESysEQFULL 106 "/* Interface output queue is full */"
check_reverse_errno_number ESysELAST 106 "/* Must be equal largest errno */"
